name: myanmar_alphabet
description: Learn Myanmar Alphabet app for children
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  confetti: ^0.7.0
  google_mobile_ads: ^5.1.0
  just_audio: ^0.9.40

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  integration_test:
    sdk: flutter

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon/app_icon.png"

flutter_native_splash:
  color: "#6C5CE7"
  image: assets/icon/app_icon.png
  android: true
  ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/audio/

  fonts:
    - family: Pyidaungsu
      fonts:
        - asset: assets/fonts/Pyidaungsu-2.5.3_Regular.ttf
        - asset: assets/fonts/Pyidaungsu-2.5.3_Bold.ttf
          weight: 700
